import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api"

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
    const { user } = useUser();

    if(!user) return null;
    
    return <div className="flex gap-4 w-full">
        <Image src={user.profileImageUrl} alt="Profile Image" width={56} height={56} className="w-16 h-16 rounded-full"/>
        <input placeholder="Type Emojis Here.." className="bg-transparent outline-none grow"/>
    </div>
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const Postview = (props: PostWithUser) => {
    const { post, author } = props;
    return (
        <div key={post.id} className="flex gap-4 p-4 border-b border-slate-400">
            <Image src={author.profileImageUrl} alt={`@${author.username}'s profile picture`} width={56} height={56} className="w-16 h-16 rounded-full"/>
            <div className="flex flex-col">
                <div className="flex gap-1 text-slate-400">
                    <span>{`@${author.username}`}</span>
                    <span className="font-thin">{` . ${dayjs(post.createdAt).fromNow()}`}</span>
                </div>
                <span>{post.content}</span>
            </div>
        </div>);
}

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if(isLoading) return <div>Loading...</div>;
  if(!data) return <div>Something went wrong.</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
          <div className="w-full md:max-w-2xl h-full border-x border-slate-400">
              <div className="flex border-b border-slate-400 p-4">
                  {!user.isSignedIn ? <SignInButton /> : <CreatePostWizard />}
              </div>
              <div className="flex flex-col">
                {data?.map((fullPost) => <Postview {...fullPost} key={fullPost.post.id}/>)}
              </div>
          </div>
      </main>
    </>
  );
};

export default Home;
